### ISSUE TITLE
Forum TLS certificate has expired

### ISSUE THREAD

**Issue by Eitot** [ViennaRSS/viennarss.github.io#37]
The forum at Cocoaforge is virtually inaccessible now.

Is it possible to get a new certificate?

**Comment by josh64x2** [comment]
I've sent an email to one of the previous contacts. I'll let you know if I hear back!
Otherwise there are a few other people I can spam. 
We really need to migrate away from cocoaforge.com because it's really annoying not having control over the actual stuff we use. 

It would be nice if they could transfer the domains etc.

**Comment by josh64x2** [comment]
This is now resolved.
